# Generated by Django 3.0.3 on 2021-01-21 22:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_investment_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('weeks_high_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weeks_low_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ex_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='portfolio.Customer')),
            ],
        ),
    ]
